GET http://localhost:3001/favicon.ico

###
DELETE http://localhost:3001/api/persons/1

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Liisa Marttinen", 
    "number": "39-23-6423122"
}